# Generated by Django 4.0.3 on 2022-04-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzsakymai', '0002_alter_uzsakymai_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzsakymai',
            name='uzsakyta',
            field=models.BooleanField(default=False),
        ),
    ]
