# Generated by Django 4.0.3 on 2022-05-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzsakymai', '0003_uzsakymai_uzsakyta'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzsakymai',
            name='data',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='uzsakymai',
            name='is_kur',
            field=models.CharField(default='SA', help_text='Iš kur užsakyti', max_length=30, verbose_name='vieta'),
        ),
        migrations.AddField(
            model_name='uzsakymai',
            name='kiekis',
            field=models.SmallIntegerField(default=0, help_text='Koks dalių kiekis reikalingas', verbose_name='kiekis'),
        ),
    ]
