# Generated by Django 4.0.3 on 2022-04-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registracija', '0003_alter_darbulistas_options_alter_darboduomenys_suged_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='darbulistas',
            name='user',
        ),
        migrations.AlterField(
            model_name='darboduomenys',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
